name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macos-13

    steps:
      - name: Set up job
        run: echo "Setting up job..."

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Run maxim-lobanov/setup-xcode@v1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Run ./build_unsigned.sh
        run: |
          chmod +x build_unsigned.sh
          ./build_unsigned.sh

      - name: Run ./build_esign_ready_ipa.sh
        run: |
          chmod +x build_esign_ready_ipa.sh
          ./build_esign_ready_ipa.sh build/Hyper-Regedit-Key-Enabled-unsigned.ipa

      - name: Run actions/upload-artifact@v4
        uses: actions/upload-artifact@v4
        with:
          name: Hyper-Regedit-Key-Enabled-unsigned
          path: build/Hyper-Regedit-Key-Enabled-unsigned.ipa
          
